[package]
name = "websocket"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "websocket-server"
path = "src/main.rs"

[[bin]]
name = "websocket-client"
path = "src/client.rs"

[dependencies]
actix-files.workspace = true
actix-web.workspace = true
actix-ws.workspace = true
awc.workspace = true

env_logger.workspace = true
futures-util = { workspace = true, features = ["sink"] }
log.workspace = true
ractor = { version = "0.15", default-features = false }
tokio = { workspace = true, features = ["full"] }
tokio-stream.workspace = true
